id: PEF60ADBF
initial_creation_type: input
source_metadata:
  title: Chomden Rigpé Raldri
  language: en
  description: 'Texts by and about Chomden Rigpé Raldri (bcom ldan rig pa''i ral gri,
    1227–1305), a celebrated scholar connected with Narthang Monastery:'
  volume:
    f704f12c1bfc477db1a40f448024b8ed:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      parent: Abhidharma
created_at: '2022-02-28T22:48:44.148742'
last_modified_at: '2022-02-28T22:48:44.148748'
